run:
  skip-dirs:
    - pkg/analyzer/testdata

linters-settings:
  golint:
    min-confidence: 0
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  gci:
    local-prefixes: github.com/kulti/thelper
  depguard:
    rules:
      all:
        files:
          - $all
        allow:
          - $gostd
          # Approved orgs.
          - "github.com/gostaticanalysis/analysisutil"
          - "github.com/kulti/thelper/pkg/analyzer"

linters:
  enable-all: true
  disable:
  - lll
  - prealloc
  - dupl
  - wsl
  - nlreturn
  - goerr113
  - exhaustivestruct
  - paralleltest
  - gomnd
  - gocognit
  - nestif
  - varnamelen
  - interfacer
  - maligned
  - scopelint
  - golint
  - cyclop
  - nilnil
  - deadcode
  - varcheck
  - ifshort
  - nosnakecase
  - structcheck
  - exhaustruct
